name: Publish QuipuClient to PyPI

on:
  push:
    branches:
      - main  # or specify the branch you want to trigger the action

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install deps
        run: poetry install

      - name: Run tests
        run: poetry run pytest

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        env:
        run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}